apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-client
---
apiVersion: v1
kind: Service
metadata:
  name: curl-client
  labels:
    app: curl-client
    service: curl-client
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: curl-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-client
  template:
    metadata:
      labels:
        app: curl-client
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: curl-client
      containers:
        - name: curl-client
          image: curlimages/curl
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "infinity"]
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/curl-client/tls
      volumes:
        - name: secret-volume
          secret:
            secretName: curl-client-secret
            optional: true
---
